const translations={
es:{
skipContent:"SALTAR AL CONTENIDO",
brandSubtitle:"GRUPO EMPRESARIAL INTERNACIONAL",navHome:"INICIO",navAbout:"NOSOTROS",navServices:"SERVICIOS",navDestinations:"DESTINOS",navContact:"CONTACTO",schedule:"AGENDAR REUNI�N",
heroEyebrow:"DESARROLLAMOS OPORTUNIDADES",heroLine1:"Conectamos oportunidades.",heroLine2:"Construimos confianza.",heroCopy:"Un grupo empresarial internacional que conecta personas, proyectos e inversiones mediante relaciones s�lidas, alianzas estrat�gicas y m�s de dos d�cadas de experiencia.",knowUs:"CONOC� RCO & ASOCIADOS",explore:"EXPLORAR DESTINOS",trustLine:"M�S DE 20 A�OS GENERANDO VALOR",
visionTitle:"VISI�N INTERNACIONAL",visionText:"Conectamos mercados y oportunidades con aliados locales.",alliancesTitle:"ALIANZAS ESTRAT�GICAS",alliancesText:"Relaciones duraderas basadas en confianza y reputaci�n.",projectsTitle:"DESARROLLO DE PROYECTOS",projectsText:"Acompa�amiento desde la oportunidad hasta la ejecuci�n.",integrityTitle:"INTEGRIDAD Y RESULTADOS",integrityText:"Transparencia, compromiso y acci�n en cada etapa.",
aboutLabel:"NOSOTROS",aboutTitle:"Una red de confianza construida durante m�s de dos d�cadas.",aboutText1:"RCO comenz� en 2003 como empresa constructora. Hoy evoluciona como grupo empresarial internacional para desarrollar oportunidades, generar alianzas estrat�gicas y conectar personas, proyectos e inversiones.",aboutText2:"No somos una inmobiliaria tradicional. Somos un nexo confiable entre experiencia local, visi�n internacional y capacidad operativa.",founded:"A�o de origen",markets:"Mercados estrat�gicos",years:"A�os de experiencia",reputation:"Reputaci�n, relaciones y resultados.",
servicesLabel:"LO QUE HACEMOS",servicesTitle:"Una red. M�ltiples oportunidades.",servicesIntro:"Integramos conocimiento, conexiones y capacidad de ejecuci�n para transformar oportunidades en proyectos con valor.",s1t:"OPORTUNIDADES E INVERSIONES",s1d:"Identificaci�n, an�lisis y conexi�n con oportunidades reales.",s2t:"PROYECTOS Y PROPIEDADES",s2d:"Presentaci�n, captaci�n y desarrollo de activos seleccionados.",s3t:"CONSTRUCCI�N Y EJECUCI�N",s3d:"Obras, reformas y soluciones integrales con equipos profesionales.",s4t:"ADMINISTRACI�N INTEGRAL",s4d:"Gesti�n, mantenimiento, alquileres y soporte para propietarios.",s5t:"ALIANZAS INTERNACIONALES",s5d:"Socios locales y relaciones de confianza en mercados estrat�gicos.",s6d:"El brazo operativo para mantenimiento y cuidado integral de propiedades.",enterLiving:"INGRESAR A RCO LIVING ?",
destLabel:"PRESENCIA INTERNACIONAL",destTitle:"Oportunidades sin fronteras.",destIntro:"Visi�n global y acci�n local en destinos con identidad, crecimiento y potencial.",brazil:"Pernambuco, Porto de Galinhas y Nordeste brasile�o.",patagonia:"Bariloche, Villa La Angostura y escenarios excepcionales.",baires:"Negocios, conectividad y oportunidades de desarrollo.",spain:"Conexiones entre Europa y Am�rica Latina.",usa:"Mercados s�lidos, conexiones y oportunidades internacionales.",
livingTitle:"Cuidamos propiedades. Construimos tranquilidad.",livingText:"Una divisi�n operativa de RCO & Asociados para mantenimiento, administraci�n, inspecciones, limpieza y atenci�n integral de propiedades.",openLiving:"ABRIR RCO LIVING",requestService:"SOLICITAR SERVICIO",
talk:"HABLEMOS",contactTitle:"Las mejores oportunidades comienzan con una conversaci�n.",contactText:"Contanos tu proyecto, propiedad u oportunidad. Nuestro equipo te responder� de manera personal.",name:"Nombre",phone:"WhatsApp",email:"Correo electr�nico",interest:"�En qu� podemos ayudarte?",optInvestment:"Inversiones y oportunidades",optProperty:"Propiedades y proyectos",optLiving:"RCO Living / mantenimiento",optAlliance:"Alianza estrat�gica",message:"Mensaje",sendWhatsApp:"ENVIAR POR WHATSAPP",
footerText:"Conectamos personas, proyectos e inversiones mediante una red internacional basada en confianza, reputaci�n y relaciones de largo plazo.",footerDest:"DESTINOS",footerServices:"SERVICIOS",footerContact:"CONTACTO",fInvest:"Inversiones",fProjects:"Proyectos",fAdmin:"Administraci�n",fAlliances:"Alianzas",rights:"Todos los derechos reservados."
},
pt:{
skipContent:"PULAR PARA O CONTE�DO",
brandSubtitle:"GRUPO EMPRESARIAL INTERNACIONAL",navHome:"IN�CIO",navAbout:"SOBRE N�S",navServices:"SERVI�OS",navDestinations:"DESTINOS",navContact:"CONTATO",schedule:"AGENDAR REUNI�O",
heroEyebrow:"DESENVOLVEMOS OPORTUNIDADES",heroLine1:"Conectamos oportunidades.",heroLine2:"Constru�mos confian�a.",heroCopy:"Um grupo empresarial internacional que conecta pessoas, projetos e investimentos por meio de rela��es s�lidas, alian�as estrat�gicas e mais de duas d�cadas de experi�ncia.",knowUs:"CONHE�A A RCO & ASSOCIADOS",explore:"EXPLORAR DESTINOS",trustLine:"MAIS DE 20 ANOS GERANDO VALOR",
visionTitle:"VIS�O INTERNACIONAL",visionText:"Conectamos mercados e oportunidades com parceiros locais.",alliancesTitle:"ALIAN�AS ESTRAT�GICAS",alliancesText:"Rela��es duradouras baseadas em confian�a e reputa��o.",projectsTitle:"DESENVOLVIMENTO DE PROJETOS",projectsText:"Acompanhamento desde a oportunidade at� a execu��o.",integrityTitle:"INTEGRIDADE E RESULTADOS",integrityText:"Transpar�ncia, compromisso e a��o em cada etapa.",
aboutLabel:"SOBRE N�S",aboutTitle:"Uma rede de confian�a constru�da ao longo de mais de duas d�cadas.",aboutText1:"A RCO come�ou em 2003 como empresa de constru��o. Hoje evolui como grupo empresarial internacional para desenvolver oportunidades, gerar alian�as estrat�gicas e conectar pessoas, projetos e investimentos.",aboutText2:"N�o somos uma imobili�ria tradicional. Somos uma ponte confi�vel entre experi�ncia local, vis�o internacional e capacidade operacional.",founded:"Ano de origem",markets:"Mercados estrat�gicos",years:"Anos de experi�ncia",reputation:"Reputa��o, rela��es e resultados.",
servicesLabel:"O QUE FAZEMOS",servicesTitle:"Uma rede. M�ltiplas oportunidades.",servicesIntro:"Integramos conhecimento, conex�es e capacidade de execu��o para transformar oportunidades em projetos de valor.",s1t:"OPORTUNIDADES E INVESTIMENTOS",s1d:"Identifica��o, an�lise e conex�o com oportunidades reais.",s2t:"PROJETOS E PROPRIEDADES",s2d:"Apresenta��o, capta��o e desenvolvimento de ativos selecionados.",s3t:"CONSTRU��O E EXECU��O",s3d:"Obras, reformas e solu��es integrais com equipes profissionais.",s4t:"ADMINISTRA��O INTEGRAL",s4d:"Gest�o, manuten��o, loca��es e suporte para propriet�rios.",s5t:"ALIAN�AS INTERNACIONAIS",s5d:"Parceiros locais e rela��es de confian�a em mercados estrat�gicos.",s6d:"O bra�o operacional para manuten��o e cuidado integral de propriedades.",enterLiving:"ENTRAR NA RCO LIVING ?",
destLabel:"PRESEN�A INTERNACIONAL",destTitle:"Oportunidades sem fronteiras.",destIntro:"Vis�o global e a��o local em destinos com identidade, crescimento e potencial.",brazil:"Pernambuco, Porto de Galinhas e Nordeste brasileiro.",patagonia:"Bariloche, Villa La Angostura e cen�rios excepcionais.",baires:"Neg�cios, conectividade e oportunidades de desenvolvimento.",spain:"Conex�es entre Europa e Am�rica Latina.",usa:"Mercados s�lidos, conex�es e oportunidades internacionais.",
livingTitle:"Cuidamos de propriedades. Constru�mos tranquilidade.",livingText:"Uma divis�o operacional da RCO & Associados para manuten��o, administra��o, inspe��es, limpeza e atendimento integral de propriedades.",openLiving:"ABRIR RCO LIVING",requestService:"SOLICITAR SERVI�O",
talk:"VAMOS CONVERSAR",contactTitle:"As melhores oportunidades come�am com uma conversa.",contactText:"Conte-nos sobre seu projeto, propriedade ou oportunidade. Nossa equipe responder� de forma pessoal.",name:"Nome",phone:"WhatsApp",email:"E-mail",interest:"Como podemos ajudar?",optInvestment:"Investimentos e oportunidades",optProperty:"Propriedades e projetos",optLiving:"RCO Living / manuten��o",optAlliance:"Alian�a estrat�gica",message:"Mensagem",sendWhatsApp:"ENVIAR PELO WHATSAPP",
footerText:"Conectamos pessoas, projetos e investimentos por meio de uma rede internacional baseada em confian�a, reputa��o e rela��es de longo prazo.",footerDest:"DESTINOS",footerServices:"SERVI�OS",footerContact:"CONTATO",fInvest:"Investimentos",fProjects:"Projetos",fAdmin:"Administra��o",fAlliances:"Alian�as",rights:"Todos os direitos reservados."
},
en:{
skipContent:"SKIP TO CONTENT",
brandSubtitle:"INTERNATIONAL BUSINESS GROUP",navHome:"HOME",navAbout:"ABOUT",navServices:"SERVICES",navDestinations:"DESTINATIONS",navContact:"CONTACT",schedule:"SCHEDULE A MEETING",
heroEyebrow:"WE DEVELOP OPPORTUNITIES",heroLine1:"Connecting opportunities.",heroLine2:"Building trust.",heroCopy:"An international business group connecting people, projects and investments through strong relationships, strategic alliances and more than two decades of experience.",knowUs:"DISCOVER RCO & ASSOCIATES",explore:"EXPLORE DESTINATIONS",trustLine:"OVER 20 YEARS CREATING VALUE",
visionTitle:"INTERNATIONAL VISION",visionText:"We connect markets and opportunities through trusted local partners.",alliancesTitle:"STRATEGIC ALLIANCES",alliancesText:"Long-term relationships built on trust and reputation.",projectsTitle:"PROJECT DEVELOPMENT",projectsText:"Support from opportunity identification through execution.",integrityTitle:"INTEGRITY AND RESULTS",integrityText:"Transparency, commitment and action at every stage.",
aboutLabel:"ABOUT US",aboutTitle:"A network of trust built over more than two decades.",aboutText1:"RCO began in 2003 as a construction company. Today it is evolving into an international business group that develops opportunities, creates strategic alliances and connects people, projects and investments.",aboutText2:"We are not a traditional real estate agency. We are a trusted link between local expertise, international vision and operational capacity.",founded:"Founded",markets:"Strategic markets",years:"Years of experience",reputation:"Reputation, relationships and results.",
servicesLabel:"WHAT WE DO",servicesTitle:"One network. Multiple opportunities.",servicesIntro:"We bring together knowledge, connections and execution capacity to turn opportunities into valuable projects.",s1t:"OPPORTUNITIES AND INVESTMENTS",s1d:"Identification, analysis and connection with real opportunities.",s2t:"PROJECTS AND PROPERTIES",s2d:"Presentation, sourcing and development of selected assets.",s3t:"CONSTRUCTION AND DELIVERY",s3d:"Construction, renovations and integrated solutions with professional teams.",s4t:"INTEGRATED MANAGEMENT",s4d:"Management, maintenance, rentals and owner support.",s5t:"INTERNATIONAL ALLIANCES",s5d:"Trusted local partners and long-term relationships in strategic markets.",s6d:"Our operational division for complete property care and maintenance.",enterLiving:"ENTER RCO LIVING ?",
destLabel:"INTERNATIONAL PRESENCE",destTitle:"Opportunities without borders.",destIntro:"Global vision and local action in destinations with identity, growth and potential.",brazil:"Pernambuco, Porto de Galinhas and Northeast Brazil.",patagonia:"Bariloche, Villa La Angostura and exceptional landscapes.",baires:"Business, connectivity and development opportunities.",spain:"Connecting Europe and Latin America.",usa:"Strong markets, connections and international opportunities.",
livingTitle:"We care for properties. We build peace of mind.",livingText:"An operational division of RCO & Associates providing maintenance, management, inspections, cleaning and complete property support.",openLiving:"OPEN RCO LIVING",requestService:"REQUEST A SERVICE",
talk:"LET'S TALK",contactTitle:"The best opportunities begin with a conversation.",contactText:"Tell us about your project, property or opportunity. Our team will reply personally.",name:"Name",phone:"WhatsApp",email:"Email",interest:"How can we help?",optInvestment:"Investments and opportunities",optProperty:"Properties and projects",optLiving:"RCO Living / maintenance",optAlliance:"Strategic alliance",message:"Message",sendWhatsApp:"SEND VIA WHATSAPP",
footerText:"We connect people, projects and investments through an international network built on trust, reputation and long-term relationships.",footerDest:"DESTINATIONS",footerServices:"SERVICES",footerContact:"CONTACT",fInvest:"Investments",fProjects:"Projects",fAdmin:"Management",fAlliances:"Alliances",rights:"All rights reserved."
}};
const supported=["es","pt","en"];
const browserLang=(navigator.language||"es").slice(0,2).toLowerCase();
let current=localStorage.getItem("rco_lang")||(supported.includes(browserLang)?browserLang:"es");
function setLang(lang){
 current=lang;localStorage.setItem("rco_lang",lang);document.documentElement.lang=lang;
 document.querySelectorAll("[data-i18n]").forEach(el=>{const k=el.dataset.i18n;if(translations[lang][k])el.textContent=translations[lang][k]});
 document.querySelectorAll("[data-lang]").forEach(b=>b.classList.toggle("active",b.dataset.lang===lang));
 const waMessages={
  es:{meeting:"Hola RCO & Asociados, quiero coordinar una reuni�n.",info:"Hola RCO & Asociados, quiero recibir informaci�n."},
  pt:{meeting:"Ol� RCO & Associados, gostaria de agendar uma reuni�o.",info:"Ol� RCO & Associados, gostaria de receber informa��es."},
  en:{meeting:"Hello RCO & Associates, I would like to schedule a meeting.",info:"Hello RCO & Associates, I would like more information."}
 };
 document.querySelectorAll("[data-wa]").forEach(link=>{link.href=`https://wa.me/5581998991468?text=${encodeURIComponent(waMessages[lang][link.dataset.wa])}`});
 const metaDescriptions={
  es:"Grupo empresarial internacional dedicado al desarrollo de oportunidades, alianzas estrat�gicas y conexi�n entre personas, proyectos e inversiones.",
  pt:"Grupo empresarial internacional dedicado ao desenvolvimento de oportunidades, alian�as estrat�gicas e conex�o entre pessoas, projetos e investimentos.",
  en:"An international business group developing opportunities, strategic alliances and connections between people, projects and investments."
 };
 document.querySelector('meta[name="description"]')?.setAttribute("content",metaDescriptions[lang]);
}
document.querySelectorAll("[data-lang]").forEach(b=>b.onclick=()=>setLang(b.dataset.lang));
setLang(current);
const menuToggle=document.querySelector(".menu-toggle");
if(menuToggle)menuToggle.onclick=e=>{const nav=document.querySelector(".nav");nav.classList.toggle("open");e.currentTarget.setAttribute("aria-expanded",nav.classList.contains("open"))};
document.querySelectorAll(".nav a").forEach(a=>a.onclick=()=>document.querySelector(".nav")?.classList.remove("open"));
document.addEventListener("keydown",event=>{if(event.key==="Escape"){document.querySelector(".nav")?.classList.remove("open");menuToggle?.setAttribute("aria-expanded","false")}});
const contactForm=document.getElementById("contactForm");
if(contactForm)contactForm.onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);const labels={es:"Inter�s",pt:"Interesse",en:"Interest"};const intros={es:"Hola RCO & Asociados, quiero recibir informaci�n.",pt:"Ol� RCO & Associados, gostaria de receber informa��es.",en:"Hello RCO & Associates, I would like more information."};const txt=[intros[current],"",f.get("name"),`WhatsApp: ${f.get("phone")}`,`Email: ${f.get("email")||"-"}`,`${labels[current]}: ${f.get("interest")}`,f.get("message")||""].join("\n");window.open(`https://wa.me/5581998991468?text=${encodeURIComponent(txt)}`,"_blank","noopener")};
const year=document.getElementById("year");if(year)year.textContent=new Date().getFullYear();
